# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trp_g', models.FloatField()),
                ('thr_g', models.FloatField()),
                ('ile_g', models.FloatField()),
                ('leu_g', models.FloatField()),
                ('lys_g', models.FloatField()),
                ('met_g', models.FloatField()),
                ('cys_g', models.FloatField()),
                ('phe_g', models.FloatField()),
                ('tyr_g', models.FloatField()),
                ('val_g', models.FloatField()),
                ('his_g', models.FloatField()),
                ('arg_g', models.FloatField()),
                ('ala_g', models.FloatField()),
                ('asp_g', models.FloatField()),
                ('glu_g', models.FloatField()),
                ('gly_g', models.FloatField()),
                ('pro_g', models.FloatField()),
                ('ser_g', models.FloatField()),
                ('prot', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbo', models.FloatField()),
                ('fiber', models.FloatField()),
                ('ash', models.FloatField()),
                ('alc', models.FloatField(null=True)),
                ('water', models.FloatField()),
                ('energ', models.FloatField()),
                ('prot_adj', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
                ('ca', models.FloatField()),
                ('fe', models.FloatField()),
                ('mg', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('na', models.FloatField()),
                ('zn', models.FloatField()),
                ('cu', models.FloatField()),
                ('mn', models.FloatField()),
                ('se', models.FloatField(null=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
