# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0005_auto_20161019_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
