# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0007_foodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='address_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
