# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0009_nutriment_rda_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriment',
            name='abbreviations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
