# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0010_nutriment_abbreviations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutriment',
            name='RDA_AI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
