# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-24 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0012_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='showQuestion',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
