# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0014_auto_20161226_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturereference',
            name='reference_APA',
            field=models.TextField(),
        ),
    ]
