# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0015_auto_20161226_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereference',
            name='supports_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aminoApp.QuestionAnswer'),
        ),
    ]
