# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0016_literaturereference_supports_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSupportsAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aminoApp.QuestionAnswer')),
            ],
        ),
        migrations.RemoveField(
            model_name='literaturereference',
            name='supports_answer',
        ),
        migrations.AddField(
            model_name='referencesupportsanswer',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aminoApp.LiteratureReference'),
        ),
    ]
