# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0017_auto_20161226_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picture_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
