# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-31 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0018_food_picture_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriment',
            name='formula',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
