# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-31 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0019_nutriment_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutriment',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
