# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0020_auto_20161231_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=80)),
                ('long_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aminoApp.QuestionTheme'),
        ),
    ]
