# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0021_auto_20170102_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='rank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
