# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoApp', '0025_recipe_aa_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='aa_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
